version: "3.9"

services:
  db:
    image: postgres:16
    container_name: ecommerce-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 080425
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
    networks:
      - ecommerce-net
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: ecommerce-backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: 080425
      DB_NAME: ecommerce_db
      DB_PORT: 5432
    ports:
      - "3000:3000"
    networks:
      - ecommerce-net
    volumes:
      - .:/app
    command: npm start

networks:
  ecommerce-net:

volumes:
  db_data:
